name: Build & Ship

on:
  push:
    branches:
      - develop

jobs:
  desktop-build:
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Download and Extract JBR
        run: |
          mkdir -p C:\jbr
          curl -L -o C:\jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.11-windows-x64-b1312.2.tar.gz

      - name: Configure JAVA_HOME
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: C:\jbr.tar.gz
          java-version: '17.0.11'
          architecture: x64

      - name: Build exe app
        run: |
          .\gradlew packageUberJarForCurrentOS
          .\gradlew createDistributable
          .\gradlew packageExe
          .\gradlew packageReleaseExe

      - name: Archive Artifacts Debug
        uses: actions/upload-artifact@v4
        with:
          name: Windows Debug
          if-no-files-found: ignore
          path: build/compose/binaries/main/exe

      - name: Archive Artifacts Release
        uses: actions/upload-artifact@v4
        with:
          name: Windows Release
          if-no-files-found: ignore
          path: build/compose/binaries/main-release/exe