name: pull request check

on:
  pull_request

jobs:
  check:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install danger
        run: |
          gem install danger danger-junit danger-checkstyle_format
      - name: Run test
        run: |
          ./gradlew test
        continue-on-error: true
      - name: Run ktlint
        run: |
          ./gradlew ktlintCheck
        continue-on-error: true
      - name: Run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          danger
